# This is a basic workflow to help you get started with Actions

name: "Publish Application"
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2

      - name: Publish
        run: dotnet publish Blazor_Wasm_IFCjs/Blazor-Wasm/Blazor-Wasm.csproj -c Release -o release --nologo

      - name: GitHub Pages
        if: ${{ github.ref == 'refs/heads/master' }}
        # You may pin to the exact commit or the version.
        # uses: crazy-max/ghaction-github-pages@db4476a01402e1a7ce05f41832040eef16d14925
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          github_token: ${{ secrets.PUBLISH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: /release/wwwroot
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
