# This is a basic workflow to help you get started with Actions

name: "Publish Application"
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2

      - name: Publish
        run: dotnet publish Blazor_Wasm_IFCjs/Blazor-Wasm/Blazor-Wasm.csproj -c Release -o release --nologo
          
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
